version: "1"

projects:
  - name: QR Restaurant Frontend
    environments:
      - name: Production
        services:
          - type: web
            name: qr-restaurant-frontend
            env: node
            plan: free
            region: oregon
            buildCommand: npm install && npx expo install @expo/webpack-config && npx expo export:web
            startCommand: npx serve -s web-build -l 10000
            envVars:
              - key: NODE_ENV
                value: production
              - key: REACT_APP_API_URL
                value: https://qr-restaurant-backend-q9g2.onrender.com/api
              - key: REACT_APP_SOCKET_URL
                value: https://qr-restaurant-backend-q9g2.onrender.com
              - key: PORT
                value: 10000
            autoDeployTrigger: commit

